### ISSUE TITLE
Delete artifact

### ISSUE THREAD

**Issue by md2manoppello** [MDEGroup/MDEForge#16]
From the list of artifacts in "MyArtifacts" I should be able to permanently delete artifacts.

**Comment by md2manoppello** [comment]
@davidediruscio  Va bene se li elimino dall'utente e li lascio comunque nel sistema?

**Comment by davidediruscio** [comment]
Da qualche parte. Devo avere la possibilità di eliminarli definitivamente.

2015-09-26 10:12 GMT+02:00 Juri Di Rocco <notifications@github.com>:

> @davidediruscio <https://github.com/davidediruscio> Va bene se li elimino
> dall'utente e li lascio comunque nel sistema?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MDEGroup/MDEForge/issues/16#issuecomment-143409117>.
>



-- 
-------------------------------------------------------------------------------------------------------------
Davide Di Ruscio, PhD in Computer Science
Department of Information Engineering Computer Science and Mathematics
University of L'Aquila
Via Vetoio, Coppito I-67010 L'Aquila (Italy)
Email: davide.diruscio@univaq.it
WWW:   http://www.di.univaq.it/diruscio
Skype: davidediruscio
Twitter: DDiRuscio
-------------------------------------------------------------------------------------------------------------
