### ISSUE TITLE
wrong resources link in jsp and js

### ISSUE THREAD

**Issue by md2manoppello** [MDEGroup/MDEForge#68]
Check all resource link. Use${pageContext.request.contextPath} in jsp page and ctx variable in js file.

**Comment by giuseppebianchi** [comment]
UPDATED:

webapp/resources/theme/scripts/myscripts/dyamicRow.js

webapp/resources/theme/scripts/plugins/forms/template/comment.html
webapp/resources/theme/scripts/plugins/forms/template/projectInArtifact.html
webapp/resources/theme/scripts/plugins/forms/template/resultEcoreSearchByExampleTemplate.html

webapp/WEB-INF/views/errors/code/metric-exception.jsp

webapp/WEB-INF/views/private/use/dashboard.jsp
webapp/WEB-INF/views/private/use/metamodel_compare.jsp
webapp/WEB-INF/views/private/use/my_artifacts_generated.jsp
webapp/WEB-INF/views/private/use/my_artifacts.jsp
webapp/WEB-INF/views/private/use/my_models_generated.jsp
webapp/WEB-INF/views/private/use/my_models.jsp
webapp/WEB-INF/views/private/use/workspace_details.jsp

webapp/WEB-INF/views/public/front/about.jsp
webapp/WEB-INF/views/public/front/dashboard.jsp
